namespace MathStat.Styles
{
    public enum ThemeResourceKey
    {
        ButtonControlDefaultBorder,
        ButtonControlFocusBorder,
        ButtonControlFocusBorderThickness,
        ButtonControlMouseOverBackground,
        ButtonControlMouseOverBorder,
        ButtonControlPressedBackground,
        ButtonControlPressedBorder,
        ButtonCornerRadius,
        /////////////////////////
        ControlDisabledOpacity,
        ///
        HeaderButtonControlBorderThickness,
        HeaderButtonControlBorderColor,
        HeaderButtonControlBackgroundColor,
        HeaderButtonControlDefaultColor,
        HeaderButtonControlOpacity,
        ///
        WindowBorder,
        WindowBackground,
        WindowForeground,
        WindowBorderThickness,
        WindowHeaderBackground,
        WindowHeaderForeground,
        WindowMouseOverBackground
    }
}
